### PR TITLE
Fixed delayed end touch issues and added tap event handler

### PR DESCRIPTION
**Pull request by michaeltyson**
Hi! A few things:

1. Replaced the UIView touch handlers with a gesture recognizer, as there is an iOS quirk (okay, let's call it what it is: bug) that delays the touchesEnded method at random, causing mayhem. This quirk doesn't apply to gesture recognizers.
2. Added tap event handler (brief touch without any movement - good for an additional fire control, for instance)
3. Use relative position for joystick control, rather than absolute, meaning it's less critical where the first touch occurs.

### CODE REVIEW

**Comment by bradhowes** [comment]
Hi Michael, thanks so much for your additions!

**Comment by michaeltyson** [comment]
My pleasure! Looks like the unit tests are failing because of the modified behaviour (relative control).

**Comment by bradhowes** [comment]
@michaeltyson I've reworked your change to continue supporting the `tappedBlock` modification while also fixing the tests and the interaction with the double-tap revert base to origin. I think I found the problem with the delayed `touchesEnded` reporting -- see the code for `installSingleTapGestureRecognizer` and `installDoubleTapGestureRecognizer` functions. Finally, I added a delay to the reporting out of handle position if `tappedBlock` is not nil so that a tap event would not trigger a movement report. Let me know if this still works for you. Thanks again for your efforts.

**Comment by michaeltyson** [comment]
Cool!

Sadly this seems to break a bunch of stuff for me - the delay on the tap now stops the stick from reacting at all for that duration, making it near impossible to use. It also has broken the relative control, which means that if your finger hits the pad anywhere but the centre, it starts movement at a speed relative to the offset from the centre, which I at least find very difficult to control. I'll be leaving these changes out of the Quake 2 iOS port PR I think.

**Comment by bradhowes** [comment]
Gah! Sorry about that. I think I have things sorted so default behavior is still there, but your relative stuff works again. For it to work, you must set `handlePositionMode` to be `.relative`. That should give you what you were after from the start. I have added a UI test to verify this behavior.

**Comment by michaeltyson** [comment]
Cool, thanks for that! Sorry for the delayed response there, been doing other things.

**Pull request merged**
